# Helper: generates all 4 compare_fN_trace.ps1 files
# Run once then delete.

function Make-CompareScript($frameNum) {
    $n = $frameNum
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# compare_f${n}_trace.ps1")
    $lines.Add("# Compare nes1 and FCEUX per-scanline / per-write traces for Frame ${n}")
    $lines.Add("# of Mappy (Japan) - comprehensive comparison of all CPU+PPU state.")
    $lines.Add("")
    $lines.Add('$RomPath    = ' + "'C:\Work\nes1\test\Mappy (Japan).nes'")
    $lines.Add('$Nes1Exe    = ' + "'C:\Work\nes1\src\x64\Debug\nes1.exe'")
    $lines.Add('$OutDir     = ' + "'C:\Work\nes1\test\mappy_out'")
    $lines.Add('$Nes1Trace  = "$OutDir\nes1_sl_f' + "${n}.txt" + '"')
    $lines.Add('$FceuxTrace = "$OutDir\fceux_sl_f' + "${n}.txt" + '"')
    $lines.Add('$OutHtml    = "$OutDir\f' + "${n}_compare.html" + '"')
    $lines.Add('$TargetFrame = ' + $n)
    $lines.Add("")
    $lines.Add('Write-Host "Running nes1 --scanlinetrace for frame $TargetFrame ..."')
    $lines.Add('$null = New-Item -ItemType Directory -Path $OutDir -Force')
    $lines.Add('& $Nes1Exe $RomPath --scanlinetrace $Nes1Trace $TargetFrame')
    $lines.Add('if (-not (Test-Path $Nes1Trace)) { Write-Error "nes1 trace not generated: $Nes1Trace"; exit 1 }')
    $lines.Add('Write-Host "  -> $Nes1Trace"')
    $lines.Add("")
    $lines.Add('if (-not (Test-Path $FceuxTrace)) {')
    $lines.Add('    Write-Warning "FCEUX trace not found: $FceuxTrace -- run mappy_f' + "${n}_trace.lua in FCEUX first." + '"')
    $lines.Add("}")
    $lines.Add("")
    $lines.Add("function Parse-TraceFile(`$path) {")
    $lines.Add("    `$result = @{ Part1 = @(); Part2 = @(); Found = `$false }")
    $lines.Add("    if (-not (Test-Path `$path)) { return `$result }")
    $lines.Add("    `$result.Found = `$true")
    $lines.Add("    `$part = ''")
    $lines.Add("    foreach (`$line in [System.IO.File]::ReadAllLines(`$path)) {")
    $lines.Add("        if (`$line -match '^=== PART1') { `$part = 'P1'; continue }")
    $lines.Add("        if (`$line -match '^=== PART2') { `$part = 'P2'; continue }")
    $lines.Add("        if (`$line -match '^\s*#') { continue }")
    $lines.Add("        if ([string]::IsNullOrWhiteSpace(`$line)) { continue }")
    $lines.Add("        `$tok = `$line.Trim() -split '\s+'")
    $lines.Add("        if (`$part -eq 'P1' -and `$tok.Count -ge 19) {")
    $lines.Add("            `$result.Part1 += @{")
    $lines.Add("                SL=`$([int]`$tok[0]); V_S=`$tok[1]; V_E=`$tok[2]; T_E=`$tok[3]")
    $lines.Add("                FX=`$tok[4]; W=`$tok[5]; CTL=`$tok[6]; MSK=`$tok[7]")
    $lines.Add("                SSX=`$tok[8]; SS_Y=`$tok[9]; SSNT=`$tok[10]")
    $lines.Add("                NTw=`$([int]`$tok[11]); CYC=`$tok[12]")
    $lines.Add("                PC=`$tok[13]; A=`$tok[14]; X=`$tok[15]; Y=`$tok[16]; S=`$tok[17]; P=`$tok[18]")
    $lines.Add("                PAL=( if (`$tok.Count -ge 20) { `$tok[19] } else { '?' } )")
    $lines.Add("            }")
    $lines.Add("        } elseif (`$part -eq 'P2' -and `$tok.Count -ge 7) {")
    $lines.Add("            `$result.Part2 += @{")
    $lines.Add("                SEQ=`$([int]`$tok[0]); SL=`$tok[1]; DOT=`$tok[2]")
    $lines.Add("                V_BEF=`$tok[3]; V_AFT=`$tok[4]; NTADDR=`$tok[5]")
    $lines.Add("                VAL=`$tok[6]; PC=( if (`$tok.Count -ge 8) { `$tok[7] } else { '?' } )")
    $lines.Add("            }")
    $lines.Add("        }")
    $lines.Add("    }")
    $lines.Add("    return `$result")
    $lines.Add("}")
    $lines.Add("")
    $lines.Add('Write-Host "Parsing traces..."')
    $lines.Add('$nes1  = Parse-TraceFile $Nes1Trace')
    $lines.Add('$fceux = Parse-TraceFile $FceuxTrace')
    $lines.Add('Write-Host "  nes1:  $($nes1.Part1.Count) SLs, $($nes1.Part2.Count) writes"')
    $lines.Add('Write-Host "  fceux: $($fceux.Part1.Count) SLs, $($fceux.Part2.Count) writes"')
    $lines.Add("")
    $lines.Add('$nes1_p1  = @{}; foreach ($r in $nes1.Part1)  { $nes1_p1[$r.SL]  = $r }')
    $lines.Add('$fceux_p1 = @{}; foreach ($r in $fceux.Part1) { $fceux_p1[$r.SL] = $r }')
    $lines.Add("")
    $lines.Add('$sl_rows = @()')
    $lines.Add('for ($sl = 0; $sl -lt 240; $sl++) {')
    $lines.Add('    $n = $nes1_p1[$sl]; $f = $fceux_p1[$sl]')
    $lines.Add('    $row = @{ SL=$sl; N=$n; F=$f }')
    $lines.Add('    $row.VS_Match  = $n -and $f -and ($n.V_S  -eq $f.V_S)')
    $lines.Add('    $row.VE_Match  = $n -and $f -and ($n.V_E  -eq $f.V_E)')
    $lines.Add('    $row.TE_Match  = $n -and $f -and ($n.T_E  -eq $f.T_E)')
    $lines.Add('    $row.FX_Match  = $n -and $f -and ($n.FX   -eq $f.FX)')
    $lines.Add('    $row.W_Match   = $n -and $f -and ($n.W    -eq $f.W)')
    $lines.Add('    $row.CTL_Match = $n -and $f -and ($n.CTL  -eq $f.CTL)')
    $lines.Add('    $row.MSK_Match = $n -and $f -and ($n.MSK  -eq $f.MSK)')
    $lines.Add('    $row.NTw_Match = $n -and $f -and ($n.NTw  -eq $f.NTw)')
    $lines.Add('    $row.PC_Match  = $n -and $f -and ($n.PC   -eq $f.PC)')
    $lines.Add('    $row.A_Match   = $n -and $f -and ($n.A    -eq $f.A)')
    $lines.Add('    $row.X_Match   = $n -and $f -and ($n.X    -eq $f.X)')
    $lines.Add('    $row.Y_Match   = $n -and $f -and ($n.Y    -eq $f.Y)')
    $lines.Add('    $row.S_Match   = $n -and $f -and ($n.S    -eq $f.S)')
    $lines.Add('    $row.P_Match   = $n -and $f -and ($n.P    -eq $f.P)')
    $lines.Add('    $row.PAL_Match = $n -and $f -and ($n.PAL  -eq $f.PAL)')
    $lines.Add('    $row.Any_Diff  = $n -and $f -and (-not (')
    $lines.Add('        $row.VS_Match -and $row.VE_Match -and $row.TE_Match -and')
    $lines.Add('        $row.FX_Match -and $row.W_Match  -and $row.CTL_Match -and $row.MSK_Match -and')
    $lines.Add('        $row.NTw_Match -and $row.PC_Match -and $row.A_Match  -and $row.X_Match -and')
    $lines.Add('        $row.Y_Match  -and $row.S_Match  -and $row.P_Match  -and $row.PAL_Match')
    $lines.Add('    ))')
    $lines.Add('    $sl_rows += $row')
    $lines.Add("}")
    $lines.Add("")
    $lines.Add('$max_seq = [Math]::Max($nes1.Part2.Count, $fceux.Part2.Count)')
    $lines.Add('$w_rows  = @()')
    $lines.Add('for ($i = 0; $i -lt $max_seq; $i++) {')
    $lines.Add('    $n = if ($i -lt $nes1.Part2.Count)  { $nes1.Part2[$i]  } else { $null }')
    $lines.Add('    $f = if ($i -lt $fceux.Part2.Count) { $fceux.Part2[$i] } else { $null }')
    $lines.Add('    $row = @{ SEQ=($i+1); N=$n; F=$f }')
    $lines.Add('    $row.SL_Match     = $n -and $f -and ($n.SL     -eq $f.SL)')
    $lines.Add('    $row.NTADDR_Match = $n -and $f -and ($n.NTADDR -eq $f.NTADDR)')
    $lines.Add('    $row.VAL_Match    = $n -and $f -and ($n.VAL    -eq $f.VAL)')
    $lines.Add('    $row.Any_Diff     = $n -and $f -and (-not ($row.SL_Match -and $row.NTADDR_Match -and $row.VAL_Match))')
    $lines.Add('    $row.Missing      = (-not $n) -or (-not $f)')
    $lines.Add('    $w_rows += $row')
    $lines.Add("}")
    $lines.Add("")
    $lines.Add('$sl_diff_v   = ($sl_rows | Where-Object { $_.N -and $_.F -and (-not $_.VE_Match) }).Count')
    $lines.Add('$sl_diff_ntw = ($sl_rows | Where-Object { $_.N -and $_.F -and (-not $_.NTw_Match) }).Count')
    $lines.Add('$sl_diff_pal = ($sl_rows | Where-Object { $_.N -and $_.F -and (-not $_.PAL_Match) }).Count')
    $lines.Add('$sl_diff_cpu = ($sl_rows | Where-Object { $_.N -and $_.F -and (-not ($_.PC_Match -and $_.A_Match -and $_.X_Match -and $_.Y_Match -and $_.S_Match -and $_.P_Match)) }).Count')
    $lines.Add("")
    $lines.Add('Write-Host "Generating HTML report..."')
    $lines.Add("")
    $lines.Add('function ce($s) { if ($null -eq $s) { return "" }; [System.Net.WebUtility]::HtmlEncode([string]$s) }')
    $lines.Add('$sb = [System.Text.StringBuilder]::new()')
    $lines.Add('$null = $sb.Append(' + "'<!DOCTYPE html><html lang=" + '"' + "en" + '"' + "><head><meta charset=" + '"' + "utf-8" + '"' + "><title>Frame ${n} Trace Compare - Mappy</title>')")
    $lines.Add('$null = $sb.Append(' + "'<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:Consolas,monospace;font-size:12px;background:#1a1b26;color:#c0caf5}')")
    $lines.Add('$null = $sb.Append(' + "'.page-hdr{background:#24283b;padding:10px 18px;position:sticky;top:0;z-index:200;border-bottom:2px solid #414868;display:flex;align-items:center;gap:16px;flex-wrap:wrap}')")
    $lines.Add('$null = $sb.Append(' + "'.page-hdr h1{font-size:15px;color:#bb9af7;white-space:nowrap}')")
    $lines.Add('$null = $sb.Append(' + "'.badge{background:#2e3348;border-radius:4px;padding:2px 9px;font-size:11px;white-space:nowrap}.badge.ok{background:#1a2b1a;color:#9ece6a}.badge.bad{background:#2d1a1a;color:#f7768e}')")
    $lines.Add('$null = $sb.Append(' + "'.controls{background:#1f2335;padding:6px 18px;border-bottom:1px solid #414868;display:flex;gap:18px;align-items:center;position:sticky;top:41px;z-index:199}')")
    $lines.Add('$null = $sb.Append(' + "'.controls label{cursor:pointer;color:#a9b1d6;font-size:11px}input[type=checkbox]{accent-color:#bb9af7;margin-right:4px;cursor:pointer}')")
    $lines.Add('$null = $sb.Append(' + "'.section{padding:14px 18px 6px}.section-title{font-size:13px;color:#7dcfff;padding-bottom:5px;border-bottom:1px solid #414868;margin-bottom:8px}')")
    $lines.Add('$null = $sb.Append(' + "'.wrap{overflow-x:auto;margin-bottom:20px}table{border-collapse:collapse;width:100%;font-size:11px}')")
    $lines.Add('$null = $sb.Append(' + "'th{background:#24283b;color:#a9b1d6;padding:3px 6px;text-align:left;white-space:nowrap;border-bottom:2px solid #414868}th.sl-col{background:#1f2335}')")
    $lines.Add('$null = $sb.Append(' + "'th.nes-h{border-top:3px solid #7aa2f7;background:#1e2535}th.fcx-h{border-top:3px solid #ff9e64;background:#251e2a}th.cmp-h{border-top:3px solid #565f89;background:#1f2335;color:#565f89}')")
    $lines.Add('$null = $sb.Append(' + "'td{padding:2px 6px;border-bottom:1px solid #1e2030;white-space:nowrap;color:#c0caf5}tr:hover td{background:#292e42}td.na{color:#3b3f5c}')")
    $lines.Add('$null = $sb.Append(' + "'td.ind{text-align:center;font-size:11px;width:16px}td.ind.ok{color:#9ece6a}td.ind.bad{color:#f7768e;font-weight:bold}td.ind.na{color:#3b3f5c}')")
    $lines.Add('$null = $sb.Append(' + "'td.diff{color:#f7768e;font-weight:bold}tr.row-bad{background:#1f1826}tr.row-hidden{display:none}')")
    $lines.Add('$null = $sb.Append(' + "'.sep-nes{border-left:2px solid #7aa2f7}.sep-fcx{border-left:2px solid #ff9e64}.sep-cmp{border-left:1px solid #414868}')")
    $lines.Add('$null = $sb.Append(' + "'.pal-box{font-family:Consolas,monospace;font-size:10px}</style></head><body>')")
    $lines.Add('$badVE  = if ($sl_diff_v   -gt 0) { "bad" } else { "ok" }')
    $lines.Add('$badNTW = if ($sl_diff_ntw -gt 0) { "bad" } else { "ok" }')
    $lines.Add('$badPAL = if ($sl_diff_pal -gt 0) { "bad" } else { "ok" }')
    $lines.Add('$badCPU = if ($sl_diff_cpu -gt 0) { "bad" } else { "ok" }')
    $lines.Add('$null = $sb.Append("<div class=''page-hdr''><h1>Frame ' + $n + ' Trace Compare &mdash; Mappy (Japan)</h1>")')
    $lines.Add('$null = $sb.Append("<span class=''badge''>nes1 P2: $($nes1.Part2.Count)</span><span class=''badge''>fceux P2: $($fceux.Part2.Count)</span>")')
    $lines.Add('$null = $sb.Append("<span class=''badge $badVE''>V_E diffs: $sl_diff_v/240</span><span class=''badge $badNTW''>NTw diffs: $sl_diff_ntw/240</span>")')
    $lines.Add('$null = $sb.Append("<span class=''badge $badPAL''>PAL diffs: $sl_diff_pal/240</span><span class=''badge $badCPU''>CPU diffs: $sl_diff_cpu/240</span></div>")')
    $lines.Add('$null = $sb.Append("<div class=''controls''><label><input type=''checkbox'' id=''chk1'' onchange=''filterP1()''> Part 1 diffs only</label>")')
    $lines.Add('$null = $sb.Append("<label><input type=''checkbox'' id=''chk2'' onchange=''filterP2()''> Part 2 diffs only</label></div>")')
    $lines.Add('# PART 1 table')
    $lines.Add('$null = $sb.Append("<div class=''section''><div class=''section-title''>Part 1 &mdash; Per-Scanline (240 rows)</div><div class=''wrap''><table id=''tbl1''><thead>")')
    $lines.Add('$null = $sb.Append("<tr><th rowspan=''2'' class=''sl-col''>SL</th>")')
    $lines.Add('$null = $sb.Append("<th colspan=''8'' class=''nes-h sep-nes''>nes1</th>")')
    $lines.Add('$null = $sb.Append("<th colspan=''8'' class=''fcx-h sep-fcx''>FCEUX</th>")')
    $lines.Add('$null = $sb.Append("<th colspan=''15'' class=''cmp-h sep-cmp''>match? (= ok, &lt;&gt; diff)</th></tr>")')
    $lines.Add('$null = $sb.Append("<tr><th class=''nes-h sep-nes''>V_S</th><th class=''nes-h''>V_E</th><th class=''nes-h''>T_E</th><th class=''nes-h''>CTL</th><th class=''nes-h''>MSK</th><th class=''nes-h''>NTw</th><th class=''nes-h''>CYC</th><th class=''nes-h''>PC</th>")')
    $lines.Add('$null = $sb.Append("<th class=''fcx-h sep-fcx''>V_S</th><th class=''fcx-h''>V_E</th><th class=''fcx-h''>T_E</th><th class=''fcx-h''>CTL</th><th class=''fcx-h''>MSK</th><th class=''fcx-h''>NTw</th><th class=''fcx-h''>CYC</th><th class=''fcx-h''>PC</th>")')
    $lines.Add('$null = $sb.Append("<th class=''cmp-h sep-cmp''>V_S</th><th class=''cmp-h''>V_E</th><th class=''cmp-h''>T_E</th><th class=''cmp-h''>CTL</th><th class=''cmp-h''>MSK</th><th class=''cmp-h''>NTw</th><th class=''cmp-h''>PC</th>")')
    $lines.Add('$null = $sb.Append("<th class=''cmp-h''>A</th><th class=''cmp-h''>X</th><th class=''cmp-h''>Y</th><th class=''cmp-h''>S</th><th class=''cmp-h''>P</th><th class=''cmp-h''>FX</th><th class=''cmp-h''>W</th><th class=''cmp-h''>PAL</th></tr></thead><tbody>")')
    $lines.Add('$first_diff_p1 = -1')
    $lines.Add('foreach ($row in $sl_rows) {')
    $lines.Add('    $n = $row.N; $f = $row.F')
    $lines.Add('    $hasN = $null -ne $n; $hasF = $null -ne $f')
    $lines.Add('    $isDiff = $row.Any_Diff')
    $lines.Add('    $trCls = if ($isDiff) { "row-bad" } else { "row-ok" }')
    $lines.Add('    $dd = if ($isDiff) { " data-diff=''1''" } else { "" }')
    $lines.Add('    $null = $sb.Append("<tr class=''$trCls''$dd><td>$($row.SL)</td>")')
    $lines.Add('    $cols = @(' + "'V_S','V_E','T_E','CTL','MSK','NTw','CYC','PC'" + ')')
    $lines.Add('    $first = $true')
    $lines.Add('    foreach ($col in $cols) {')
    $lines.Add('        $nv = if ($hasN) { $n.$col } else { $null }')
    $lines.Add('        $fv = if ($hasF) { $f.$col } else { $null }')
    $lines.Add('        $bad = $hasN -and $hasF -and ($nv -ne $fv)')
    $lines.Add('        $cls = if ($bad) { ' + "'diff'" + ' } else { ' + "'val'" + ' }')
    $lines.Add('        $sep = if ($first) { ' + "' sep-nes'" + ' } else { ' + "''" + ' }; $first = $false')
    $lines.Add('        if ($hasN) { $null = $sb.Append("<td class=''$cls$sep''>$(ce $nv)</td>") } else { $null = $sb.Append("<td class=''na$sep''>-</td>") }')
    $lines.Add('    }')
    $lines.Add('    $first = $true')
    $lines.Add('    foreach ($col in $cols) {')
    $lines.Add('        $nv = if ($hasN) { $n.$col } else { $null }')
    $lines.Add('        $fv = if ($hasF) { $f.$col } else { $null }')
    $lines.Add('        $bad = $hasN -and $hasF -and ($nv -ne $fv)')
    $lines.Add('        $cls = if ($bad) { ' + "'diff'" + ' } else { ' + "'val'" + ' }')
    $lines.Add('        $sep = if ($first) { ' + "' sep-fcx'" + ' } else { ' + "''" + ' }; $first = $false')
    $lines.Add('        if ($hasF) { $null = $sb.Append("<td class=''$cls$sep''>$(ce $fv)</td>") } else { $null = $sb.Append("<td class=''na$sep''>-</td>") }')
    $lines.Add('    }')
    $lines.Add('    $matchCols = @(' + "'VS_Match','VE_Match','TE_Match','CTL_Match','MSK_Match','NTw_Match','PC_Match','A_Match','X_Match','Y_Match','S_Match','P_Match','FX_Match','W_Match','PAL_Match'" + ')')
    $lines.Add('    $first = $true')
    $lines.Add('    foreach ($mc in $matchCols) {')
    $lines.Add('        $sep = if ($first) { ' + "' sep-cmp'" + ' } else { ' + "''" + ' }; $first = $false')
    $lines.Add('        if (-not $hasN -or -not $hasF) { $null = $sb.Append("<td class=''ind na$sep''>-</td>") }')
    $lines.Add('        elseif ($row.$mc) { $null = $sb.Append("<td class=''ind ok$sep''>=</td>") }')
    $lines.Add('        else { $null = $sb.Append("<td class=''ind bad$sep''>&lt;&gt;</td>") }')
    $lines.Add('    }')
    $lines.Add('    $null = $sb.Append("</tr>")')
    $lines.Add('    if ($first_diff_p1 -lt 0 -and $isDiff) { $first_diff_p1 = $row.SL }')
    $lines.Add("}")
    $lines.Add('$null = $sb.Append("</tbody></table></div>")')
    $lines.Add('if ($first_diff_p1 -ge 0) { $null = $sb.Append("<p style=''color:#f7768e;font-size:11px;margin-bottom:6px''>First difference at scanline $first_diff_p1</p>") }')
    $lines.Add('# Palette diff detail')
    $lines.Add('$palDiffSLs = @($sl_rows | Where-Object { $_.N -and $_.F -and (-not $_.PAL_Match) })')
    $lines.Add('if ($palDiffSLs.Count -gt 0) {')
    $lines.Add('    $null = $sb.Append("<div class=''section-title'' style=''color:#ff9e64;margin-top:10px''>Palette Differences ($($palDiffSLs.Count) scanlines)</div>")')
    $lines.Add('    $null = $sb.Append("<div class=''wrap''><table><thead><tr><th>SL</th><th>Side</th>")')
    $lines.Add('    for ($b = 0; $b -lt 32; $b++) { $null = $sb.Append("<th>$b</th>") }')
    $lines.Add('    $null = $sb.Append("</tr></thead><tbody>")')
    $lines.Add('    foreach ($row in $palDiffSLs) {')
    $lines.Add('        $np = $row.N.PAL; $fp = $row.F.PAL')
    $lines.Add('        if ($np.Length -lt 64 -or $fp.Length -lt 64) { continue }')
    $lines.Add('        $null = $sb.Append("<tr class=''row-bad''><td rowspan=''2''>$($row.SL)</td><td class=''sep-nes''>nes1</td>")')
    $lines.Add('        for ($b = 0; $b -lt 32; $b++) {')
    $lines.Add('            $nb = $np.Substring($b*2,2); $fb = $fp.Substring($b*2,2)')
    $lines.Add('            $cls = if ($nb -ne $fb) { "diff" } else { "val" }')
    $lines.Add('            $null = $sb.Append("<td class=''pal-box $cls''>$nb</td>")')
    $lines.Add('        }')
    $lines.Add('        $null = $sb.Append("</tr>")')
    $lines.Add('        $null = $sb.Append("<tr class=''row-bad''><td class=''sep-fcx''>fceux</td>")')
    $lines.Add('        for ($b = 0; $b -lt 32; $b++) {')
    $lines.Add('            $nb = $np.Substring($b*2,2); $fb = $fp.Substring($b*2,2)')
    $lines.Add('            $cls = if ($nb -ne $fb) { "diff" } else { "val" }')
    $lines.Add('            $null = $sb.Append("<td class=''pal-box $cls''>$fb</td>")')
    $lines.Add('        }')
    $lines.Add('        $null = $sb.Append("</tr>")')
    $lines.Add('    }')
    $lines.Add('    $null = $sb.Append("</tbody></table></div>")')
    $lines.Add("}")
    $lines.Add('$null = $sb.Append("</div>")')
    $lines.Add('# PART 2 table')
    $lines.Add('$null = $sb.Append("<div class=''section''><div class=''section-title''>Part 2 &mdash; NT Write Log (nes1: $($nes1.Part2.Count) | fceux: $($fceux.Part2.Count))</div><div class=''wrap''><table id=''tbl2''><thead>")')
    $lines.Add('$null = $sb.Append("<tr><th>SEQ</th><th class=''nes-h sep-nes''>SL</th><th class=''nes-h''>NTADDR</th><th class=''nes-h''>VAL</th><th class=''nes-h''>V_BEF</th><th class=''nes-h''>V_AFT</th><th class=''nes-h''>PC</th>")')
    $lines.Add('$null = $sb.Append("<th class=''fcx-h sep-fcx''>SL</th><th class=''fcx-h''>NTADDR</th><th class=''fcx-h''>VAL</th><th class=''fcx-h''>V_BEF</th><th class=''fcx-h''>V_AFT</th><th class=''fcx-h''>PC</th>")')
    $lines.Add('$null = $sb.Append("<th class=''cmp-h sep-cmp''>SL</th><th class=''cmp-h''>NTADDR</th><th class=''cmp-h''>VAL</th></tr></thead><tbody>")')
    $lines.Add('$first_diff_p2 = -1')
    $lines.Add('foreach ($row in $w_rows) {')
    $lines.Add('    $n = $row.N; $f = $row.F')
    $lines.Add('    $hasN = $null -ne $n; $hasF = $null -ne $f')
    $lines.Add('    $isDiff = $row.Any_Diff -or $row.Missing')
    $lines.Add('    $trCls = if ($row.Missing) { "row-na" } elseif ($isDiff) { "row-bad" } else { "row-ok" }')
    $lines.Add('    $dd = if ($isDiff) { " data-diff=''1''" } else { "" }')
    $lines.Add('    $null = $sb.Append("<tr class=''$trCls''$dd><td>$($row.SEQ)</td>")')
    $lines.Add('    $p2cols = @(' + "'SL','NTADDR','VAL','V_BEF','V_AFT','PC'" + ')')
    $lines.Add('    $first = $true')
    $lines.Add('    foreach ($col in $p2cols) {')
    $lines.Add('        $nv = if ($hasN) { $n.$col } else { $null }')
    $lines.Add('        $fv = if ($hasF) { $f.$col } else { $null }')
    $lines.Add('        $bad = $hasN -and $hasF -and ($nv -ne $fv)')
    $lines.Add('        $cls = if ($bad) { ' + "'diff'" + ' } else { ' + "'val'" + ' }')
    $lines.Add('        $sep = if ($first) { ' + "' sep-nes'" + ' } else { ' + "''" + ' }; $first = $false')
    $lines.Add('        if ($hasN) { $null = $sb.Append("<td class=''$cls$sep''>$(ce $nv)</td>") } else { $null = $sb.Append("<td class=''na$sep''>-</td>") }')
    $lines.Add('    }')
    $lines.Add('    $first = $true')
    $lines.Add('    foreach ($col in $p2cols) {')
    $lines.Add('        $nv = if ($hasN) { $n.$col } else { $null }')
    $lines.Add('        $fv = if ($hasF) { $f.$col } else { $null }')
    $lines.Add('        $bad = $hasN -and $hasF -and ($nv -ne $fv)')
    $lines.Add('        $cls = if ($bad) { ' + "'diff'" + ' } else { ' + "'val'" + ' }')
    $lines.Add('        $sep = if ($first) { ' + "' sep-fcx'" + ' } else { ' + "''" + ' }; $first = $false')
    $lines.Add('        if ($hasF) { $null = $sb.Append("<td class=''$cls$sep''>$(ce $fv)</td>") } else { $null = $sb.Append("<td class=''na$sep''>-</td>") }')
    $lines.Add('    }')
    $lines.Add('    $mcs = @(' + "'SL_Match','NTADDR_Match','VAL_Match'" + ')')
    $lines.Add('    $first = $true')
    $lines.Add('    foreach ($mc in $mcs) {')
    $lines.Add('        $sep = if ($first) { ' + "' sep-cmp'" + ' } else { ' + "''" + ' }; $first = $false')
    $lines.Add('        if ($row.Missing) { $null = $sb.Append("<td class=''ind na$sep''>-</td>") }')
    $lines.Add('        elseif ($row.$mc) { $null = $sb.Append("<td class=''ind ok$sep''>=</td>") }')
    $lines.Add('        else { $null = $sb.Append("<td class=''ind bad$sep''>&lt;&gt;</td>") }')
    $lines.Add('    }')
    $lines.Add('    $null = $sb.Append("</tr>")')
    $lines.Add('    if ($first_diff_p2 -lt 0 -and $isDiff) { $first_diff_p2 = $row.SEQ }')
    $lines.Add("}")
    $lines.Add('$null = $sb.Append("</tbody></table></div></div>")')
    $lines.Add('$null = $sb.Append(' + "'<script>function filterP1(){ var s=document.getElementById(" + '"chk1"' + ").checked; document.querySelectorAll(" + '"#tbl1 tbody tr"' + ").forEach(function(r){ r.classList.toggle(" + '"row-hidden"' + ",s&&!r.dataset.diff); }); }')")
    $lines.Add('$null = $sb.Append(' + "'function filterP2(){ var s=document.getElementById(" + '"chk2"' + ").checked; document.querySelectorAll(" + '"#tbl2 tbody tr"' + ").forEach(function(r){ r.classList.toggle(" + '"row-hidden"' + ",s&&!r.dataset.diff); }); }</script></body></html>')")
    $lines.Add('[System.IO.File]::WriteAllText($OutHtml, $sb.ToString(), [System.Text.Encoding]::UTF8)')
    $lines.Add('Write-Host "HTML written to $OutHtml"')
    return $lines
}

foreach ($fn in 1,2,3,4) {
    $path = "C:\Work\nes1\test\compare_f${fn}_trace.ps1"
    $content = Make-CompareScript $fn
    [System.IO.File]::WriteAllLines($path, $content, [System.Text.Encoding]::UTF8)
    Write-Host "Wrote $path ($($content.Count) lines)"
}
